### PR TITLE
Allow to download file from context menu

### PR DESCRIPTION
**Pull request by wacki4**
I've needed sometimes to download file to other location than opening in atom (for example graphics). I've added possibility for open dialog to ask user where to save a file.

### CODE REVIEW

**Comment by cschindl** [comment]
Hi @wacki4,

the idea is great, but it would be nice if you could not only select files but also directories to download them. You should also check locally if the file or directory already exists. Here you should be prompted to overwrite or cancel. 

It would be best to create the functions "downloadFile" and "downloadDirectory" in ftp-remote-edit.js. We could use these later also for other functions like the "uploadFile", "uploadDirectory" function.

I would rename the current function "downloadFile" to "download" and only check here whether a file or a directory should be downloaded. Then I would call the appropriate function.

**Comment by wacki4** [comment]
@cschindl - the dialog has possibility to show prompt if it should overwrite file or not. Isn't it enought ? :)

**Comment by cschindl** [comment]
Yes that fits one of the requirements ;)

**Comment by wacki4** [comment]
So i've started on this one, it looks simpler.

**Comment by wacki4** [comment]
So... see this one ;) Work in progress, any thoughts on this stage?

**Comment by cschindl** [comment]
You should clean and format your code but everything else looks good ;)

**Comment by wacki4** [comment]
Done ;)

**Pull request merged**
