### PR TITLE
Allow to forced reopen file.

### PR DESCRIPTION
**Pull request by wacki4**
Reopen file from context menu, and also main config option for reopening when click on item.

### CODE REVIEW

**Comment by wacki4** [comment]
As asked in #239

**Comment by th23x** [comment]
@cschindl Would really like to see this feature taken up into your extension - it would allow for an easy way to (auto)-reload eg logfiles on a server once they are changes (with new entries). As pointed out it would solve the reported issued #239 that I came across as well - and would really be a good enhancement to this great Atom extension :-)

**Comment by cschindl** [comment]
@wacki4 the pull request does not include download of the file. It only close the file tab? Please check this again. So I cannot release it unfortunately. And adapt immediately to the new data structure. In the file-view.js there is no open function anymore. These are all moved to ftp-remote-edit.js.

**Comment by wacki4** [comment]
I will try to check it after completing grouping - probably bad merge.

**Comment by wacki4** [comment]
I think that it would make a work. I have now broken config file, but as i see code, it should do the work.

also - in ftp-remote-edit.js do You use anytime openRemoteFile ? I couldn't find any use of it.

**Comment by cschindl** [comment]
It is used as provided service. Look into the package.json. The Juno editor use this plugin and needed the service. I will check your changes tomorrow.

**Comment by felixholub** [comment]
Any news on this functionality? For log-files this would be extremely useful.

**Comment by cschindl** [comment]
Hi @felixholub,

you can reload an already opened file by right-clicking and selecting "reload". The same works for expanded directories. This has already been done with release [0.15.0](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.15.0).

**Comment by felixholub** [comment]
Thank you @cschindl ! Would it be possible to invoke a reload from a double-click?

**Comment by cschindl** [comment]
The double-click function is already used for pending pane items. If you have enabled the "Allow pending pane items" option in the preferences, a single click opens the file in the preview and a double click opens the file permanently. The behavior here is exactly the same as with the atom editor.

**Comment by felixholub** [comment]
Okay, thank you. I'm migrating from remote-ftp where a simple double-click reloads a file. This explains the confusion.

**Pull request closed without merging**
