### PR TITLE
Allow to upload file from context menu

### PR DESCRIPTION
**Pull request by wacki4**
Also done uploading multiple files from local to remote using context menu instead of drag&drop.

### CODE REVIEW

**Comment by cschindl** [comment]
Hi @wacki4,

the idea is great, but it would be nice if you could not only select files but also directories to upload them. 

It would be best to create the function "upload" in ftp-remote-edit.js which only check here whether a file or a directory should be uploaded. Then I would call the appropriate already existing function (uploadFile, uploadDirectory).

**Comment by wacki4** [comment]
So... which first? Maybe You would like to help with one of them? Or You don't have time for it so i should make both on free time?

**Comment by cschindl** [comment]
I can finish your work (upload / download) because I have some free time at the moment. Download would be more complex than upload. So I would start with that.

**Comment by wacki4** [comment]
I now started download, upload looks for me more complex? Maybe teamwork, You would look at upload then, i will try download, if i stop somewhere or would need some help i will write to You on pull request.

For now directory is creating ;)

**Comment by cschindl** [comment]
@wacki4 I have opened a new branch "[upload-from-context-menu](https://github.com/h3imdall/ftp-remote-edit/tree/feature/upload-from-context-menu)". Here are my adjustments included. It should be finished so far. I said yes upload is a lot easier ;) But you may be able to get some of the structure for the download function here.

**Comment by wacki4** [comment]
So i think both completed... ;) Time to new release? I will try to make import.

**Comment by cschindl** [comment]
I merged both pull requests into the developer branch. But I still need this refactor the whole file, so I can use the functions uploadFile/uploadDirectory and downloadFile and downloadDirectory in the other functions.

**Pull request merged**
