### PR TITLE
Allow to select prompt for password on servers

### PR DESCRIPTION
**Pull request by wacki4**
For some servers we don't want even to save encrypted password, so added possibility to select 'prompt for password' on servers.

### CODE REVIEW

**Comment by cschindl** [comment]
Hi @wacki4,

as you already mentioned, this option only makes sense if you can open the server list without a master password. Together with your other pull request (#322), we could of course use this very well.

**Comment by wacki4** [comment]
Maybe include this one for now - for no encryption i think it would need some more work ;) It You think it is fully a good idea - i will try to make no encryption also possible and working good. I will need some help there, more 'how to' - but i will discuss it with You on private.

**Comment by cschindl** [comment]
As it extends the functionality of the plugin and does not make it more complicated, it can be used already now. But it only makes real sense when using a non-encrypted server list.

**Comment by wacki4** [comment]
Allright, and i will be working on non-encrypted ;)

**Pull request merged**
