### PR TITLE
Allow server path in uri hander

### PR DESCRIPTION
**Pull request by wacki4**
Regarding to issue #244 (The URI handler is wonderful. I would like to add functions)

### CODE REVIEW

**Comment by cschindl** [comment]
Looks good. Thank you very much for your help.

**Comment by wacki4** [comment]
Also done #239 - can reopen file from context menu, and also main config option for reopening when click on item.

**Comment by cschindl** [comment]
Hi @wacki4,

please create an individual pull request for each issue. Mixing several issues into one pull request makes it very difficult to release individual parts. In this case the adjustments for the URI handler are good and released. But I would have to reject the other adjustments. 

If files are changed locally, atom reloads them automatically. A reload is therefore not necessary. If they are changed on the ftp server, the changes are not reloaded by atom. This was the reason for the issue. The solution would be to synchronize the files with the server. Here you have to check which file version is newer.

**Comment by wacki4** [comment]
Github automaticaly sent all of them to current pull request (Add more commits by pushing to the master branch on wacki4/ftp-remote-edit.). I will try to remember to try not make such mess. Have I to open new branch for next change?

For reload - please write a comment on issue, i would not done anything or consult You first for change. Also, If You want to synchronize with server - i think that it wont be good, what You check for that? Modify date or other i think won't be good way, and if by content - it will be downloaded each time. Where i work in a team, many times someone else is reviewing code, and forced reopening like that would be great to speed up work. Also as I think from same reason #239 was created. Most of editors have such forced reload.

Also, i've made here natural sort - it is really anoing when files/directories are ordered was as now. It will be helpful if natural ordering will be implemented. If You want, i can it make optional.

**Comment by cschindl** [comment]
The best practice is to open a new branch in the fork for every new feature. For each branch you can open a separate pull request. Changes and discussions can then be made and tested in the corresponding branch. 

I will try to merge the first commit (URI handler) into an new seperate branch, so I can merge it into the master. For your other changes, please create new branches (sorting, reload) and open new pull requests.

**Pull request merged**
