### PR TITLE
Allowing to remove temporary server

### PR DESCRIPTION
**Pull request by wacki4**
Today at work i found out that removing temporary server from tree view would be really helpfull - so done one ;)

### CODE REVIEW

**Comment by cschindl** [comment]
Looks good and does what it's supposed to do! ;)

**Comment by cschindl** [comment]
I have now finished the refactoring and merged the upload/download feature and the removal of temporary servers into the development brach. This would have to be tested intensively because of some big changes.

**Comment by wacki4** [comment]
As i clicked - everything looks great, only missing thing is showing what files or folder has been uploaded or downloaded, when using folder upload/download.

**Comment by wacki4** [comment]
Maybe also on download - add buttons to open path or open file which has been downloaded?

**Comment by cschindl** [comment]
I have added the notifications for successful upload/download. But I still have to test everything. And I really mean everything, not only upload/download also create, rename, delete, move, copy, paste etc....

**Comment by wacki4** [comment]
I will try today to sit down and click everything to find any problem ;) development is current?

**Comment by cschindl** [comment]
Yes, the latest changes are still in the development branch.

**Comment by wacki4** [comment]
I've clicked everything for about an hour - everything looks great. Only think that i noticed, is still something 'wrong' in folder creation. When we create new folder, and put in inside another (look also in parent field - there not all of them are visible), and go back to server view - it looks like select is empty or don't have newly added record. After save, and going back everything looks great, so as i think i don't refresh data correctly on some of folder operation.

Everything else - masterpiece ;)

**Pull request closed without merging**
