### PR TITLE
Allows to remeber last selected path for download/upload

### PR DESCRIPTION
**Pull request by wacki4**
I've many times upload/download many files multiple time, even between servers. Getting throught each folder was annoing - so i've added possibility to remember last path while until restart.

### CODE REVIEW

**Comment by cschindl** [comment]
Hi @wacki4,

nice to hear from you again. As I see, you were once again very diligent. The idea to save the path is very good, because it is the normal behavior of the operating system. I therefore think that we can omit the configuration option and always save the last path temporarily. At the next upload/download it is enough to check if the path still exists. If so, it can be used again. Otherwise we change to the default path. What do you think?

**Comment by wacki4** [comment]
I've made is as settings - cause maybe some people would like to open only default path. Still easy, but giving more possibilites of work :) If You thing that last path should be always - i don't have any others thoughts other that above. It would be still great ;)

**Comment by cschindl** [comment]
I think the last path should always be used. Too many configuration options confuse most people. Since the behavior would then be identical to the operating system, I think most people will not miss the configuration.

**Comment by wacki4** [comment]
So remove config parameter? Or You will do it on merging ? ;)

**Comment by cschindl** [comment]
Please remove the configuration parameters. I want to make sure I don't make any mistakes when merging.

**Comment by wacki4** [comment]
Done ;)

**Pull request merged**
